# Generated by Django 4.2 on 2026-06-04 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.CharField(blank=True, max_length=300, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inv_categorias',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.CharField(blank=True, max_length=300, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=30, null=True)),
                ('controla_stock', models.BooleanField(default=True)),
                ('permite_decimal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('impuesto', models.ForeignKey(blank=True, db_column='impuesto_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='configuracion.impuesto')),
            ],
            options={
                'db_table': 'inv_productos',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_antes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_despues', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venta_detalle_id', models.IntegerField(blank=True, null=True)),
                ('compra_detalle_id', models.IntegerField(blank=True, null=True)),
                ('venta_devolucion_id', models.IntegerField(blank=True, null=True)),
                ('compra_devolucion_id', models.IntegerField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.producto')),
                ('sede', models.ForeignKey(db_column='sede_id', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='configuracion.sede')),
                ('tipo_movimiento', models.ForeignKey(db_column='tipo_movimiento_id', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='configuracion.tipomovimientoinventario')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inv_movimientos',
                'ordering': ['-fecha_movimiento'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra_detalle_id', models.IntegerField(blank=True, null=True)),
                ('numero_lote', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.producto')),
                ('sede', models.ForeignKey(db_column='sede_id', on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='configuracion.sede')),
            ],
            options={
                'db_table': 'inv_lotes',
                'ordering': ['fecha_vencimiento'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.categoria')),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='inventario.producto')),
            ],
            options={
                'db_table': 'inv_producto_categoria',
                'managed': True,
                'unique_together': {('producto', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventario.producto')),
                ('sede', models.ForeignKey(db_column='sede_id', on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='configuracion.sede')),
            ],
            options={
                'db_table': 'inv_stock',
                'ordering': ['producto__nombre'],
                'managed': True,
                'unique_together': {('producto', 'sede')},
            },
        ),
    ]
