# Generated by Django 4.2 on 2026-06-05 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': False, 'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='inventario',
            options={'managed': False, 'ordering': ['producto__nombre']},
        ),
        migrations.AlterModelOptions(
            name='movimiento',
            options={'managed': False, 'ordering': ['-fecha_movimiento']},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False, 'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='productocategoria',
            options={'managed': False},
        ),
    ]
