# Generated by Django 4.2 on 2026-06-04 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compra', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('no_factura_proveedor', models.CharField(blank=True, max_length=80, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('recibida', 'Recibida'), ('anulada', 'Anulada')], default='pendiente', max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'com_compras',
                'ordering': ['-fecha_compra'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('compra', models.ForeignKey(db_column='compra_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.compra')),
            ],
            options={
                'db_table': 'com_compra_detalle',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DevolucionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('total_devuelto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(db_column='compra_id', on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='compras.compra')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_compra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'com_devoluciones',
                'ordering': ['-fecha_devolucion'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nit', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=80, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'com_proveedores',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FacturaAbastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('emitida', 'Emitida'), ('anulada', 'Anulada')], default='emitida', max_length=10)),
                ('cufe', models.CharField(blank=True, max_length=200, null=True)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('xml_dian', models.TextField(blank=True, null=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(db_column='compra_id', on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='compras.compra')),
                ('proveedor', models.ForeignKey(db_column='proveedor_id', on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='compras.proveedor')),
                ('sede', models.ForeignKey(db_column='sede_id', on_delete=django.db.models.deletion.PROTECT, related_name='facturas_abastecimiento', to='configuracion.sede')),
            ],
            options={
                'db_table': 'com_facturas_abastecimiento',
                'ordering': ['-fecha_emision'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DevolucionCompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compra_detalle', models.ForeignKey(db_column='compra_detalle_id', on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='compras.compradetalle')),
                ('devolucion', models.ForeignKey(db_column='devolucion_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.devolucioncompra')),
            ],
            options={
                'db_table': 'com_devolucion_detalle',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
