# Generated by Django 4.2 on 2026-06-05 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'managed': False, 'ordering': ['-fecha_compra']},
        ),
        migrations.AlterModelOptions(
            name='compradetalle',
            options={'managed': False, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='devolucioncompra',
            options={'managed': False, 'ordering': ['-fecha_devolucion']},
        ),
        migrations.AlterModelOptions(
            name='facturaabastecimiento',
            options={'managed': False, 'ordering': ['-fecha_emision']},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'managed': False, 'ordering': ['nombre']},
        ),
    ]
