# Generated by Django 4.2 on 2026-06-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_documento', models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('NIT', 'NIT'), ('CE', 'Cédula de extranjería'), ('PAS', 'Pasaporte'), ('DE', 'Documento extranjero')], max_length=3, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cli_clientes',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DevolucionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('total_devuelto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ven_devoluciones',
                'ordering': ['-fecha_devolucion'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DevolucionVentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'ven_devolucion_detalle',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacturaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('nombre_cliente', models.CharField(blank=True, max_length=150, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('emitida', 'Emitida'), ('anulada', 'Anulada')], default='emitida', max_length=10)),
                ('cufe', models.CharField(blank=True, max_length=200, null=True)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('xml_dian', models.TextField(blank=True, null=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ven_facturas',
                'ordering': ['-fecha_emision'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('cambio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ven_pagos',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_venta', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('nombre_cliente', models.CharField(blank=True, max_length=150, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('completada', 'Completada'), ('anulada', 'Anulada'), ('devuelta', 'Devuelta')], default='completada', max_length=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ven_ventas',
                'ordering': ['-fecha_venta'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'ven_venta_detalle',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
